03bloco 01dia
CaioRobs/trybe_exercises pull request #6
Opened 2021-07-21 19:18 UTC by CaioRobs

2021-07-21 21:20 UTC, CaioRobs reviewed
Esse é o readme do repositorio completo, não o readme do bloco 03 dia 01

2021-07-21 23:04 UTC, GabrielJorge94 approved these changes

2021-07-22 00:30 UTC, JesseBenevides requested changes
Caio, seria legal inserir o atributo `alt` com a descrição da sua imagem
Linha 17 arquivo exemplo.html

2021-07-22 14:41 UTC, CaioRobs commented on 01_fundamentos/03bloco_html_css/01dia_intro_e_estruturas/exemplo.html
> +        <img src="SouTryber.png" width="500">
Verdade!

2021-07-22 14:43 UTC, CaioRobs commented
@JesseBenevides, adicionei o alt, confirma aí pra mim pra eu dar merge? :D

2021-07-22 15:04 UTC, CaioRobs commented on 01_fundamentos/03bloco_html_css/01dia_intro_e_estruturas/exemplo.html
> +        <img src="SouTryber.png" width="500">
(pergunta)
Como vc escreveu a linha bonitinha assim? com aspas simples?
'<img src="SouTryber.png" width="500" alt="Descrição da Imagem>'

2021-07-22 15:27 UTC, JesseBenevides commented on 01_fundamentos/03bloco_html_css/01dia_intro_e_estruturas/exemplo.html
> +        <img src="SouTryber.png" width="500">
Tem que colocar o código entre crases igual no slack -> `

2021-07-22 15:27 UTC, JesseBenevides approved these changes
Agora o código está ok, Caio. Aprovado!

2021-07-22 15:42 UTC, CaioRobs commented on 01_fundamentos/03bloco_html_css/01dia_intro_e_estruturas/exemplo.html
> +        <img src="SouTryber.png" width="500">
` crases `
e eu aqui tentando com aspas simples kkk

2021-07-22 15:42 UTC, merged