Exercicios/3.2
CaioRobs/trybe_exercises pull request #7
Opened 2021-07-22 17:57 UTC by CaioRobs

2021-07-22 19:39 UTC, RodrigoLimaJesus commented
Muito bem dividido cada passo do exercício, achei bem bacana.

2021-07-22 19:47 UTC, EricksonSiqueira requested changes

2021-07-22 19:47 UTC, EricksonSiqueira commented on 01_fundamentos/03bloco_html_css/02dia_css/index.html
> +    <link rel="stylesheet" href="style.css" />
Poderia ter adicionado o atributo type que foi ensinado na aula.
> `<link rel="stylesheet" type="text/css" " href="style.css" />`

2021-07-22 19:48 UTC, EricksonSiqueira commented
Código batendo certinho com o que foi pedido nos exercícios. Commits bem detalhados e separados, gostei bastante!

2021-07-22 21:03 UTC, CaioRobs commented on 01_fundamentos/03bloco_html_css/02dia_css/index.html
> +    <link rel="stylesheet" href="style.css" />
Eu não adicionei por que os navegadores já assimilam que é isso pois quando esse atributo(type) é omitido, eles utilizam o atributo rel pra entender qual que é. Quando rel="stylesheet" o browser automaticamente entende que o type é "text/css" :D

2021-07-22 21:04 UTC, merged

2021-07-23 12:40 UTC, EricksonSiqueira commented on 01_fundamentos/03bloco_html_css/02dia_css/index.html
> +    <link rel="stylesheet" href="style.css" />
Caramba muito legal, não sabia, valeu pela dica!